/**
 * OC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDB { 
    /**
     * Ункальный идентификатор пользователя
     */
    id: number;
    /**
     * Уникальный тектовый идентификатор пользователя
     */
    username: string;
    /**
     * Почта пользователя
     */
    email: string;
    /**
     * Пароль пользователя
     */
    password: string;
    /**
     * Время создания сущности в БД
     */
    createdAt: string;
    /**
     * Время обновления сущности в БД
     */
    updatedAt: string;
}

