version: '3.8'

services:
    frontend:
        build:
            context: .
            dockerfile: prod.frontend.Dockerfile
        container_name: frontend
        ports:
            - '8080:80'
#            - '8888:8888'
